version: "3.8"

services:
  redis:
    image: "redis:7.0"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend1:
    build: ./Server
    container_name: backend1
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  backend2:
    build: ./Server
    container_name: backend2
    ports:
      - "8082:8081"
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  mysql:
    image: "mysql:8.0"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poolClash
    ports:
      - "3306:3306"
    volumes:
      - ./Server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  client:
    build:
      args: 
        - VITE_APP_BASE_URL=http://localhost/api
        - VITE_WEBSOCKET_URL=ws://localhost/ws
      context: ./Client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file: ./Client/.env
    environment:
      - VITE_APP_BASE_URL=http://localhost/api
      - VITE_WEBSOCKET_URL=ws://localhost/ws

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - client
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the NGINX config file

networks:
  app-network:
    driver: bridge
