version: "3.8"

services:
  redis:
    image: "redis:7.0" # Redis instance
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app1:
    build: .
    container_name: app1
    ports:
      - "8081:80"
    depends_on:
      - redis
    networks:
      - app-network

  app2:
    build: .
    container_name: app2
    ports:
      - "8082:80"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
